# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    default_config: default
    configs:
        default:
            allowedContent: true
            extraAllowedContent: 'span;ul;li;table;td;style;*[id];*(*);*{*}'
            filebrowserImageBrowseRoute: browse-images
            toolbar: standard
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
