# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        article_main_image:
            quality: 75
            filters:
                thumbnail:
                    size: [1024, 512]
                    mode: inset
        thumb:
            quality: 75
            filters:
                # set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail:
                    size: [120, 90]
                    mode: outbound
