controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_admin:
    resource: ../../src/Admin/Controller/
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
