controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_admin:
    resource: ../../src/Admin/Controller/
    type: annotation
    prefix: /{_locale<%app.supported_locales%>}/admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
